// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

//extern
extern char *dropDownSelect;
extern char* idNodeSelect;
extern int32_t selectedRow;
bool checkLogin(char *acc,char *pass);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Label10(lv_event_t * e);
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label30;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container1;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Table1;
extern lv_obj_t * ui_id;
extern lv_obj_t * ui_name;
extern lv_obj_t * ui_value;
extern lv_obj_t * ui_state;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label8;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Table2;
void table_event_handler(lv_event_t * e);
extern lv_obj_t * ui_idS;
extern lv_obj_t * ui_deviceCS;
extern lv_obj_t * ui_statieS;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label13;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Label14(lv_event_t * e);
extern lv_obj_t * ui_Label14;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label15;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Dropdown5;
extern lv_obj_t * ui_Label12;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label17;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
void ui_event_TextArea4(lv_event_t * e);
extern lv_obj_t * ui_TextArea4;
void ui_event_TextArea5(lv_event_t * e);
extern lv_obj_t * ui_TextArea5;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label21;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Label20(lv_event_t * e);
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label29;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label27;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label28;
void ui_event_TextArea6(lv_event_t * e);
extern lv_obj_t * ui_TextArea6;
void ui_event_TextArea7(lv_event_t * e);
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_statieview_png);    // assets/statieView.png
LV_IMG_DECLARE(ui_img_mngnode_png);    // assets/mngNode.png
LV_IMG_DECLARE(ui_img_valuesconfig_png);    // assets/valuesConfig.png
LV_IMG_DECLARE(ui_img_configwifi_png);    // assets/configWifi.png
LV_IMG_DECLARE(ui_img_2120030137);    // assets/logout (1).png
LV_IMG_DECLARE(ui_img_439233516);    // assets/home (1).png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
