// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void loadScreen3(lv_event_t * e);
void loadScreen4(lv_event_t * e);
void addStation(lv_event_t * e);
void delStation(lv_event_t * e);
void loadValues(lv_event_t * e);
void screenload5(lv_event_t * e);
void changeValues(lv_event_t * e);
void screenLoad6(lv_event_t * e);
void configWifi(lv_event_t * e);

#ifdef __cplusplus
}
#endif

#endif
