// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button14 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button14, 36);
    lv_obj_set_height(ui_Button14, 35);
    lv_obj_set_x(ui_Button14, -134);
    lv_obj_set_y(ui_Button14, -96);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button14, &ui_img_439233516, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown5 = lv_dropdown_create(ui_Screen5);
    lv_obj_set_width(ui_Dropdown5, 158);
    lv_obj_set_height(ui_Dropdown5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown5, 75);
    lv_obj_set_y(ui_Dropdown5, -87);
    lv_obj_set_align(ui_Dropdown5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label12 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -58);
    lv_obj_set_y(ui_Label12, -104);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Station select");

    ui_Button15 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button15, 65);
    lv_obj_set_height(ui_Button15, 22);
    lv_obj_set_x(ui_Button15, -41);
    lv_obj_set_y(ui_Button15, -82);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Load");

    ui_TextArea3 = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_TextArea3, 141);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_TextArea3, 78);
    lv_obj_set_y(ui_TextArea3, -48);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "cm");
    lv_textarea_set_one_line(ui_TextArea3, true);



    ui_Label16 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -71);
    lv_obj_set_y(ui_Label16, -45);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Sensor height:");

    ui_Label18 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -67);
    lv_obj_set_y(ui_Label18, -10);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Level danger:");

    ui_Label19 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -79);
    lv_obj_set_y(ui_Label19, 25);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Turbidity danger:");

    ui_TextArea4 = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_TextArea4, 141);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_TextArea4, 79);
    lv_obj_set_y(ui_TextArea4, -11);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "cm");
    lv_textarea_set_one_line(ui_TextArea4, true);



    ui_TextArea5 = lv_textarea_create(ui_Screen5);
    lv_obj_set_width(ui_TextArea5, 141);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_TextArea5, 79);
    lv_obj_set_y(ui_TextArea5, 26);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "ntu");
    lv_textarea_set_one_line(ui_TextArea5, true);



    ui_Button16 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button16, 65);
    lv_obj_set_height(ui_Button16, 25);
    lv_obj_set_x(ui_Button16, -57);
    lv_obj_set_y(ui_Button16, 90);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Change");

    ui_Button4 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button4, 65);
    lv_obj_set_height(ui_Button4, 25);
    lv_obj_set_x(ui_Button4, 55);
    lv_obj_set_y(ui_Button4, 90);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 1);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Cannel");

    ui_Keyboard2 = lv_keyboard_create(ui_Screen5);
    lv_obj_set_width(ui_Keyboard2, 321);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 1);
    lv_obj_set_y(ui_Keyboard2, 63);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label29 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -6);
    lv_obj_set_y(ui_Label29, 64);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "");
    lv_obj_set_style_text_align(ui_Label29, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label20, ui_event_Label20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}
