// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button18 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button18, 36);
    lv_obj_set_height(ui_Button18, 35);
    lv_obj_set_x(ui_Button18, -134);
    lv_obj_set_y(ui_Button18, -96);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button18, &ui_img_439233516, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 172);
    lv_obj_set_height(ui_Container2, 32);
    lv_obj_set_x(ui_Container2, 11);
    lv_obj_set_y(ui_Container2, -97);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label22, 2);
    lv_obj_set_y(ui_Label22, 6);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Wifi conenct !");
    lv_obj_set_style_text_align(ui_Label22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 1);
    lv_obj_set_y(ui_Label23, 43);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "GIANG");

    ui_Label24 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -104);
    lv_obj_set_y(ui_Label24, -54);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "SSID:");

    ui_Label25 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -107);
    lv_obj_set_y(ui_Label25, -20);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "PASS:");

    ui_Button19 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button19, 65);
    lv_obj_set_height(ui_Button19, 25);
    lv_obj_set_x(ui_Button19, -56);
    lv_obj_set_y(ui_Button19, 53);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Config");

    ui_Button20 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button20, 65);
    lv_obj_set_height(ui_Button20, 25);
    lv_obj_set_x(ui_Button20, 53);
    lv_obj_set_y(ui_Button20, 53);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Cannel");

    ui_TextArea6 = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextArea6, 166);
    lv_obj_set_height(ui_TextArea6, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_TextArea6, 29);
    lv_obj_set_y(ui_TextArea6, -56);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea6, "name (ssid)");
    lv_textarea_set_one_line(ui_TextArea6, true);



    ui_TextArea7 = lv_textarea_create(ui_Screen6);
    lv_obj_set_width(ui_TextArea7, 166);
    lv_obj_set_height(ui_TextArea7, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_TextArea7, 30);
    lv_obj_set_y(ui_TextArea7, -19);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea7, "pass (ssid)");
    lv_textarea_set_one_line(ui_TextArea7, true);
    lv_textarea_set_password_mode(ui_TextArea7, true);



    ui_Keyboard3 = lv_keyboard_create(ui_Screen6);
    lv_obj_set_width(ui_Keyboard3, 318);
    lv_obj_set_height(ui_Keyboard3, 125);
    lv_obj_set_x(ui_Keyboard3, -2);
    lv_obj_set_y(ui_Keyboard3, 60);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label31 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -1);
    lv_obj_set_y(ui_Label31, 23);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "");
    lv_obj_set_style_text_align(ui_Label31, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button19, ui_event_Button19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea7, ui_event_TextArea7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}
