// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "stationmanager.h"

extern StationManager stationManager;

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button7, 36);
    lv_obj_set_height(ui_Button7, 35);
    lv_obj_set_x(ui_Button7, -134);
    lv_obj_set_y(ui_Button7, -96);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button7, &ui_img_439233516, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown3 = lv_dropdown_create(ui_Screen4);
    lv_obj_set_width(ui_Dropdown3, 150);
    lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown3, 78);
    lv_obj_set_y(ui_Dropdown3, -89);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label11 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -46);
    lv_obj_set_y(ui_Label11, -104);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Station scan");

    // Create the table for displaying stations
    ui_Table2 = lv_table_create(ui_Screen4);
    lv_obj_set_size(ui_Table2, 320, 240); // Set table size to match the screen size
    lv_obj_align(ui_Table2, LV_ALIGN_TOP_MID, 0, 60); // Align table at the top
    lv_obj_set_style_pad_ver(ui_Table2, 0, LV_PART_ITEMS);
    lv_obj_set_style_pad_hor(ui_Table2, 15, LV_PART_ITEMS);
    // lv_obj_set_style_text_font(ui_Table2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_table_set_col_cnt(ui_Table2, 3);  // 3 columns: ID, Device Count, Status

    lv_table_set_col_width(ui_Table2, 0, 120);   // ID column
    lv_table_set_col_width(ui_Table2, 1, 90);    // Device Count column
    lv_table_set_col_width(ui_Table2, 2, 110);   // Status column

    // Set table column titles
    lv_table_set_cell_value(ui_Table2, 0, 0, "ID");
    lv_table_set_cell_value(ui_Table2, 0, 1, "Device count");
    lv_table_set_cell_value(ui_Table2, 0, 2, "Status");

    // Assuming you have a stationManager object with a method to get the list of stations
    int row_count = 1; // Start after the header row
    String dropdown_options = "";

    for (const Station& station : stationManager.getStations()) {
        if (station.status != "scan") {
            lv_table_set_row_cnt(ui_Table2, row_count + 1); // Add a row for each station with status != "scan"
            lv_table_set_cell_value(ui_Table2, row_count, 0, station.idNode.c_str());       // ID column
            lv_table_set_cell_value_fmt(ui_Table2, row_count, 1, "%d", station.deviceCount); // Device Count column
            lv_table_set_cell_value(ui_Table2, row_count, 2, station.status.c_str());        // Status column
            row_count++;
            
        }
        else {
            dropdown_options += station.idNode + "\n";
        }
    }
    lv_obj_add_event_cb(ui_Table2, table_event_handler, LV_EVENT_CLICKED, NULL);
    // Set the dropdown options
    lv_dropdown_set_options(ui_Dropdown3, dropdown_options.c_str());
    ui_Button6 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button6, 65);
    lv_obj_set_height(ui_Button6, 22);
    lv_obj_set_x(ui_Button6, -41);
    lv_obj_set_y(ui_Button6, -82);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Add");

    ui_Button8 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button8, 65);
    lv_obj_set_height(ui_Button8, 22);
    lv_obj_set_x(ui_Button8, -64);
    lv_obj_set_y(ui_Button8, 104);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Load");

    ui_Button9 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button9, 65);
    lv_obj_set_height(ui_Button9, 22);
    lv_obj_set_x(ui_Button9, 51);
    lv_obj_set_y(ui_Button9, 103);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Delete");

    // Event Callbacks
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label14, ui_event_Label14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);
    
}
